const regioes = [
    {
        numero: 1,
        cidades: [
            "Alvorada",
            "Barra do Ribeiro",
            "Cachoeirinha",
            "Eldorado do Sul",
            "Glorinha",
            "Gravataí",
            "Guaíba",
            "Mariana Pimentel",
            "Porto Alegre",
            "Sertão Santana",
            "Viamão"
        ]
    },
    {
        numero: 2,
        cidades: [
            "Arroio dos Ratos",
            "Barão do Triunfo",
            "Butiá",
            "Charqueadas",
            "General Câmara",
            "Minas do Leão",
            "São Jerônimo",
            "Vale Verde"
        ]
    },
    {
        numero: 3,
        cidades: [
            "Alecrim",
            "Bossoroca",
            "Caibaté",
            "Campina das Missões",
            "Cândido Godói",
            "Catuípe",
            "Cerro Largo",
            "Dezesseis de Novembro",
            "Entre-Ijuís",
            "Eugênio de Castro",
            "Garruchos",
            "Giruá",
            "Guarani das Missões",
            "Itaqui",
            "Mato Queimado",
            "Maçambará",
            "Novo Machado",
            "Pirapó",
            "Porto Lucena",
            "Porto Mauá",
            "Porto Vera Cruz",
            "Porto Xavier",
            "Rolador",
            "Roque Gonzales",
            "Salvador das Missões",
            "Santa Rosa",
            "Santo Ângelo",
            "Santo Antônio das Missões",
            "Santo Cristo",
            "São Borja",
            "São Luiz Gonzaga",
            "São Miguel das Missões",
            "São Nicolau",
            "São Paulo das Missões",
            "São Pedro do Butiá",
            "Senador Salgado Filho",
            "Sete de Setembro",
            "Tucunduva",
            "Tuparendi",
            "Ubiretama",
            "Vitória das Missões"
        ]
    },
    {
        numero: 4,
        cidades: [
            "Alegrete",
            "Barra do Quaraí",
            "Quaraí",
            "Uruguaiana"
        ]
    },
    {
        numero: 5,
        cidades: [
            "Amaral Ferrador",
            "Cachoeira do Sul",
            "Candelária",
            "Encruzilhada do Sul",
            "Herveiras",
            "Novo Cabrais",
            "Pantano Grande",
            "Passo do Sobrado",
            "Rio Pardo",
            "Santa Cruz do Sul",
            "Sinimbu",
            "Vale do Sol",
            "Vera Cruz"
        ]
    },
    {
        numero: 6,
        cidades: [
            "Chuí",
            "Rio Grande",
            "Santa Vitória do Palmar",
            "São José do Norte"
        ]
    },
    {
        numero: 7,
        cidades: [
            "Água Santa",
            "Almirante Tamandaré do Sul",
            "Camargo",
            "Carazinho",
            "Casca",
            "Chapada",
            "Charrua",
            "Ciriaco",
            "Colorado",
            "Constantina",
            "Coqueiros do Sul",
            "Coxilha",
            "David Canabarro",
            "Engenho Velho",
            "Ernestina",
            "Gentil",
            "Liberato Salzano",
            "Marau",
            "Mato Castelhano",
            "Não Me Toque",
            "Nicolau Vergueiro",
            "Nova Alvorada",
            "Nova Boa Vista",
            "Passo Fundo",
            "Pontão",
            "Ronda Alta",
            "Rondinha",
            "Saldanha Marinho",
            "Santa Cecília do Sul",
            "Santo Antônio do Palma",
            "Santo Antônio do Planalto",
            "São Domingos do Sul",
            "Sarandi",
            "Sertão",
            "Tapejara",
            "Tio Hugo",
            "Três Palmeiras",
            "Vanini",
            "Victor Graeff",
            "Vila Lângaro",
            "Vila Maria"
        ]
    },
    {
        numero: 8,
        cidades: [
            "André da Rocha",
            "Antônio Prado",
            "Bom Jesus",
            "Campestre da Serra",
            "Capão Bonito do Sul",
            "Caseiros",
            "Esmeralda",
            "Ibiraiaras",
            "Ipê",
            "Lagoa Vermelha",
            "Monte Alegre dos Campos",
            "Muitos Capões",
            "Muliterno",
            "Pinhal da Serra",
            "São José dos Ausentes",
            "Vacaria"
        ]
    },
    {
        numero: 9,
        cidades: [
            "Ajuricaba",
            "Augusto Pestana",
            "Boa Vista do Cadeado",
            "Boa Vista do Incra",
            "Bozano",
            "Coronel Barros",
            "Cruz Alta",
            "Fortaleza dos Valos",
            "Ibirubá",
            "Ijuí",
            "Jari",
            "Jóia",
            "Júlio de Castilhos",
            "Nova Ramada",
            "Panambi",
            "Pejuçara",
            "Pinhal Grande",
            "Quevedos",
            "Quinze de Novembro",
            "Santa Bárbara do Sul",
            "Selbach",
            "Tupanciretã"
        ]
    },
    {
        numero: 10,
        cidades: [
            "Cacequi",
            "Capão do Cipó",
            "Itacurubi",
            "Jaguari",
            "Manoel Viana",
            "Mata",
            "Nova Esperança do Sul",
            "Santiago",
            "São Francisco de Assis",
            "São Vicente do Sul",
            "Toropi",
            "Unistalda"
        ]
    },
    {
        numero: 11,
        cidades: [
            "Bento Gonçalves",
            "Carlos Barbosa",
            "Cotiporã",
            "Dois Lageados",
            "Fagundes Varela",
            "Garibaldi",
            "Guabijú",
            "Guaporé",
            "Montauri",
            "Monte Belo do Sul",
            "Nova Araçá",
            "Nova Bassano",
            "Nova Prata",
            "Paraí",
            "Pinto Bandeira",
            "Protásio Alves",
            "Santa Tereza",
            "São Jorge",
            "São Valentim do Sul",
            "São Vendelino",
            "Serafina Corrêa",
            "União da Serra",
            "Veranópolis",
            "Vila Flores",
            "Vista Alegre do Prata"
        ]
    },
    {
        numero: 12,
        cidades: [
            "Canoas",
            "Esteio",
            "Nova Santa Rita",
            "São Leopoldo",
            "Sapucaia do Sul"
        ]
    },
    {
        numero: 13,
        cidades: [
            "Agudo",
            "Cerro Branco",
            "Dilermando de Aguiar",
            "Dona Francisca",
            "Faxinal do Soturno",
            "Formigueiro",
            "Itaara",
            "Ivorá",
            "Nova Palma",
            "Paraíso do Sul",
            "Restinga Seca",
            "Santa Maria",
            "São João do Polesini",
            "São Martinho da Serra",
            "São Pedro do Sul",
            "São Sepé",
            "Silveira Martins",
            "Vila Nova do Sul"
        ]
    },
    {
        numero: 14,
        cidades: [
            "Alto Alegre",
            "Anta Gorda",
            "Arroio do Tigre",
            "Arvorezinha",
            "Barros Cassal",
            "Campos Borges",
            "Espumoso",
            "Estrela Velha",
            "Fontoura Xavier",
            "Ibarama",
            "Ibirapuitã",
            "Ilópolis",
            "Itapuca",
            "Jacuizinho",
            "Lagoa Bonita do Sul",
            "Lagoa dos Três Cantos",
            "Lagoão",
            "Mormaço",
            "Passa Sete",
            "Putinga",
            "Salto do Jacuí",
            "São José do Herval",
            "Segredo",
            "Sobradinho",
            "Soledade",
            "Tapera",
            "Tunas"
        ]
    },
    {
        numero: 15,
        cidades: [
            "Alto Feliz",
            "Barão",
            "Bom Princípio",
            "Brochier do Maratá",
            "Capela de Santana",
            "Feliz",
            "Harmonia",
            "Linha Nova",
            "Maratá",
            "Montenegro",
            "Pareci Novo",
            "Poço das Antas",
            "Portão",
            "Salvador do Sul",
            "São José do Hortêncio",
            "São José do Sul",
            "São Pedro da Serra",
            "São Sebastião do Caí",
            "Tabaí",
            "Taquari",
            "Triunfo",
            "Tupandi",
            "Vale Real"
        ]
    },
    {
        numero: 16,
        cidades: [
            "Arambaré",
            "Camaquã",
            "Cerro Grande do Sul",
            "Chuvisca",
            "Cristal",
            "Dom Feliciano",
            "São Lourenço do Sul",
            "Sentinela do Sul",
            "Tapes"
        ]
    },
    {
        numero: 17,
        cidades: [
            "Barra Funda",
            "Boa Vista das Missões",
            "Cerro Grande",
            "Condor",
            "Dois Irmãos das Missões",
            "Erval Seco",
            "Jaboticaba", 
            "Lajeado do Bugre",
            "Novo Barreiro",
            "Novo Xingu",
            "Palmeira das Missões",
            "Pinhal",
            "Sagrada Família",
            "São José das Missões",
            "São Pedro das Missões",
            "Seberi"
        ]
    },
    {
        numero: 18,
        cidades: [
            "Aceguá",
            "Bagé",
            "Caçapava do Sul",
            "Candiota",
            "Dom Pedrito",
            "Hulha Negra",
            "Lavras do Sul",
            "Rosário do Sul",
            "Santa Margarida do Sul",
            "Santana da Boa Vista",
            "Santana do Livramento",
            "São Gabriel"
        ]
    },
    {
        numero: 19,
        cidades: [
            "Aratiba",
            "Áurea",
            "Barão do Cotegipe",
            "Barra do Rio Azul",
            "Benjamin Constant do Sul",
            "Campinas do Sul",
            "Carlos Gomes",
            "Centenário",
            "Cruzaltense",
            "Entre Rios do Sul",
            "Erebango",
            "Erechim",
            "Erval Grande",
            "Estação",
            "Faxinalzinho",
            "Floriano Peixoto",
            "Gaurama",
            "Getúlio Vargas",
            "Gramado dos Loureiros",
            "Ipiranga do Sul",
            "Itatiba do Sul",
            "Jacutinga",
            "Marcelino Ramos",
            "Mariano Moro",
            "Nonoai",
            "Paulo Bento",
            "Ponte Preta",
            "Quatro Irmãos",
            "Rio dos Índios",
            "São Valentim",
            "Severiano de Almeida",
            "Três Arroios",
            "Trindade do Sul",
            "Viadutos"
        ]
    },
    {
        numero: 20,
        cidades: [
            "Alegria",
            "Barra da Guarita",
            "Boa Vista do Buricá",
            "Bom Progresso",
            "Braga",
            "Campo Novo",
            "Chiapetta",
            "Coronel Bicaco",
            "Crissiumal",
            "Derrubadas",
            "Doutor Maurício Cardoso",
            "Esperança do Sul",
            "Horizontina",
            "Humaitá",
            "Independência",
            "Inhacorá",
            "Miraguaí",
            "Nova Candelária",
            "Redentora",
            "Santo Augusto",
            "São José do Inhacorá",
            "São Martinho",
            "São Valério do Sul",
            "Sede Nova",
            "Tenente Portela",
            "Tiradentes do Sul",
            "Três de Maio",
            "Três Passos",
            "Vista Gaucha"
        ]
    },
    {
        numero: 21,
        cidades: [
            "Arroio Grande",
            "Canguçu",
            "Cerrito",
            "Herval",
            "Jaguarão",
            "Pedras Altas",
            "Pedro Osório",
            "Pinheiro Machado",
            "Piratini"
        ]
    },
    {
        numero: 22,
        cidades: [
            "Igrejinha",
            "Parobé",
            "Riozinho",
            "Rolante",
            "Taquara",
            "Três Coroas"
        ]
    },
    {
        numero: 23,
        cidades: [
            "Arroio do Sal",
            "Balneário Pinhal",
            "Capão da Canoa",
            "Capivari do Sul",
            "Caraá",
            "Cidreira",
            "Dom Pedro de Alcântara",
            "Imbé",
            "Itati",
            "Mampituba",
            "Maquiné",
            "Morrinhos do Sul",
            "Mostardas",
            "Osório",
            "Palmares do Sul",
            "Santo Antônio da Patrulha",
            "Tavares",
            "Terra de Areia",
            "Torres",
            "Tramandaí",
            "Três Cachoeiras",
            "Três Forquilhas",
            "Xangri-lá"
        ]
    },
    {
        numero: 24,
        cidades: [
            "Arroio do Meio",
            "Boa Vista do Sul",
            "Bom Retiro do Sul",
            "Boqueirão do Leão",
            "Canudos do Vale",
            "Capitão",
            "Colinas",
            "Coqueiro Baixo",
            "Coronel Pilar",
            "Cruzeiro do Sul",
            "Doutor Ricardo",
            "Encantado",
            "Estrela",
            "Fazenda Vila Nova",
            "Forquetinha",
            "Gramado Xavier",
            "Imigrante",
            "Lajeado",
            "Marques de Souza",
            "Mato Leitão",
            "Muçum",
            "Nova Bréscia",
            "Paverama",
            "Pouso Novo",
            "Progresso",
            "Relvado",
            "Roca Sales",
            "Santa Clara do Sul",
            "Sério",
            "Teutônia",
            "Travesseiro",
            "Venâncio Aires",
            "Vespasiano Correa",
            "Westfália"
        ]
    },
    {
        numero: 25,
        cidades: [
            "Caxias do Sul",
            "Farroupilha",
            "Flores da Cunha",
            "Nova Pádua",
            "Nova Roma do Sul",
            "São Marcos"
        ]
    },
    {
        numero: 26,
        cidades: [
            "Arroio do Padre",
            "Capão do Leão",
            "Morro Redondo",
            "Pelotas",
            "Turuçu"
        ]
    },
    {
        numero: 27,
        cidades: [
            "Cambará do Sul",
            "Canela",
            "Gramado",
            "Jaquirana",
            "Nova Petrópolis",
            "Picada Café",
            "São Francisco de Paula"
        ]
    },
    {
        numero: 28,
        cidades: [
            "Alpestre",
            "Ametista do Sul",
            "Caiçara",
            "Cristal do Sul",
            "Frederico Westphalen",
            "Iraí",
            "Novo Tiradentes",
            "Palmitinho",
            "Pinheirinho do Vale",
            "Planalto",
            "Rodeio Bonito",
            "Taquaruçu do Sul",
            "Vicente Dutra",
            "Vista Alegre"
        ]
    },
    {
        numero: 29,
        cidades: [
            "Barracão",
            "Cacique Doble",
            "Ibiaçá",
            "Machadinho",
            "Maximiliano de Almeida",
            "Paim Filho",
            "Sananduva",
            "Santo Expedito do Sul",
            "São João da Urtiga",
            "São José do Ouro",
            "Tupanci do Sul"
        ]
    },
    {
        numero: 30,
        cidades: [
            "Araricá",
            "Campo Bom",
            "Dois Irmãos",
            "Estância Velha",
            "Ivoti",
            "Lindolfo Collor",
            "Morro Reuter",
            "Nova Hartz",
            "Novo Hamburgo",
            "Presidente Lucena",
            "Santa Maria do Herval",
            "Sapiranga"
        ]
    },
    {
        numero: 40,
        cidades: []
    }
]

module.exports = regioes;